# Cluster at 97% within samples
clust: Moorea_seqs.fasta
	~/SymITS2/otus_97_bysample.sh Moorea_seqs.fasta clust
	
# Uncompress sequences
Moorea_seqs.fasta: Moorea_seqs.tar.gz
	tar -xzvf Moorea_seqs.tar.gz -m
	

	
	